# =============================================================================
# Chat Application - Production Docker Compose
# =============================================================================
# Copy this file to compose.yml and adjust the values before deploying.
#
# Required steps:
# 1. Change all passwords and secrets (marked with "CHANGE_ME")
# 2. Set INITIAL_ADMIN_PASSWORD to a secure password
# 3. Configure KLIPY_API_KEY if you want GIF support
# 4. Adjust resource limits based on your server
# =============================================================================

services:
  # ===========================================================================
  # Chat Application
  # ===========================================================================
  chat:
    image: ghcr.io/valentinkolb/chat:latest
    platform: linux/amd64
    container_name: chat_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      valkey:
        condition: service_started
    environment:
      NODE_ENV: production
      PORT: 80
      APP_NAME: "Chat" # Displayed in the UI
      # Format: postgres://user:password@host:port/database
      DATABASE_URL: postgres://chat:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/chat
      # Format: redis://host:port
      REDIS_URL: redis://valkey:6379
      # Created on first startup if no users exist
      INITIAL_ADMIN_USERNAME: admin
      INITIAL_ADMIN_PASSWORD: admin
      SESSION_EXPIRY_HOURS: 168 # 7 days
      RATE_LIMIT_PER_SECOND: 60 # requests per second per user
      MAX_BOTS_PER_USER: 5
      KLIPY_API_KEY: "" # Optional: API key for GIF search (https://klipy.com)
    networks:
      - chat_internal
      - chat_external
    expose:
      - '80'

  # ===========================================================================
  # PostgreSQL Database
  # ===========================================================================
  postgres:
    image: postgres:17-alpine
    container_name: chat_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES} # Must match BUN_SQL_URL
    volumes:
      - postgres_data_chat:/var/lib/postgresql/data
    networks:
      - chat_internal
    # Do not expose to host in production
    # ports:
    #   - "5432:5432"

  # ===========================================================================
  # Valkey (Redis-compatible) - Session & Cache Store
  # ===========================================================================
  valkey:
    image: valkey/valkey:8-alpine
    container_name: chat_valkey
    restart: unless-stopped
    command: valkey-server --save 60 1 --loglevel warning --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - valkey_data_chat:/data
    networks:
      - chat_internal
    # Do not expose to host in production
    # ports:
    #   - "6379:6379"

# =============================================================================
# Volumes
# =============================================================================
volumes:
  postgres_data_chat:
  valkey_data_chat:

# =============================================================================
# Networks
# =============================================================================
networks:
  # Internal network for service communication
  chat_internal:
    name: chat_internal
  # External network for reverse proxy connection
  chat_external:
    name: chat_external
